### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by RAMitchell** [rapidsai/legate-boost#101]
The following is a list of tasks for us to make a legate-boost single-node release.

- [x] Legate.core.internal and cunumeric.internal conda packages
- [x] SWIPAT to open source legate-boost
- [x] Adopt versioning for legate-boost (https://github.com/rapidsai/legate-boost/pull/162)
- [x] Conda package for legate-boost (#115)
- [x] Documentation is publically available
- [ ] publish a stable release (v24.09.00) once there are stable `legate` and `cunumeric` 24.09 releases

This first release will target a single node user being able to install:

```shell
conda install -c some-channel legate-core cunumeric legate-boost
```

and run basic legateboost examples on multiple GPUs or CPUs. They should be able to read documention for python API functions.

**Comment by jameslamb** [comment]
> Adopt versioning for legate-boost

We're going to adopt calendar-based versioning following what cuNumeric and Legate are doing as closely as possible.

To help with that, I just tagged the latest commit on `main` as `v0.1.0`: https://github.com/rapidsai/legate-boost/releases/tag/v0.1.0. The first calendar-based version after that (`v2024.09.00`, presumably) will then be newer than that.

Having a tag in the repo is necessary for publishing pre-releases, because for those we'll follow the cuNumeric/Legate approach of using versions like `24.09.00dev{n}`, where `{n}` is "number of commits since the previous stable release (indicated by git tags)".

**Comment by jameslamb** [comment]
Now that #115 is complete, most of this is done!

I added one more item in the list at the top... we'll just want to cut a stable release of `legate-boost` (24.09.00) whenever there are stable releases of `legate` and `cunumeric`.

There are not any yet:

* https://anaconda.org/legate/legate/files
* https://anaconda.org/legate/cunumeric/files
